import { expect, test } from "@playwright/test";
import { addTablesFromSidebar, openBlankEditor } from "./helpers/editor";

test("Sample Data (SQL) is available in Export as and opens SQL output", async ({
  page,
}) => {
  await openBlankEditor(page);
  await addTablesFromSidebar(page, 1);

  await page.getByText("File", { exact: true }).click();
  await page.getByText("Export as", { exact: true }).hover();
  await page.getByText("Sample Data (SQL)", { exact: true }).click();

  await expect(page.getByText("Export", { exact: true })).toBeVisible();
  await expect(page.getByText("Sample data generated by drawDB")).toBeVisible();
  await expect(page.getByText(".sql", { exact: true })).toBeVisible();
});
